/****************************************************************************
File:				Wait.inc
Author:				Rafa³ Dubniewski
Verssion			1.0
Created:			2013.03.01
Modified:			2013.02.01
****************************************************************************/

#ifndef _CALENDAR_INC_
#define _CALENDAR_INC_

/*
RTC_YEAR:			.byte 1
RTC_MONTH:			.byte 1
RTC_DAY_OF_MONTH:	.byte 1
RTC_HOURS:			.byte 1
RTC_MINUTES:		.byte 1
RTC_SECONDS:		.byte 1

RTC_DAY_OF_YEAR:
RTC_DAY_OF_YEAR_L:	.byte 1
RTC_DAY_OF_YEAR_H:	.byte 1

RTC_DAY_OF_WEEK:	.byte 1


RTC_TICKS:			.byte 4
*/

#endif
