#ifndef _I2C_DefineTypes_inc_
#define _I2C_DefineTypes_inc_

.equ    DEVICE_VALVE_DRIVER_TYPE                    = 0x05
.equ    DEVICE_VALVE_DRIVER_I2C_ADDRES              = 0x72

.equ    DEVICE_TANK_MULTI_THERMOMETER_TYPE          = 0x06
.equ    DEVICE_TANK_MULTI_THERMOMETER_I2C_ADDRES    = 0x74

.equ    DEVICE_WALL_SENSOR_TYPE                     = 0x07
.equ    DEVICE_WALL_SENSOR_I2C_ADDRES               = 0x76

.equ    DEVICE_LIGHTING_CONTROLER_TYPE				= 0x08
.equ    DEVICE_LIGHTING_CONTROLER_I2C_ADDRES		= 0x78

#endif
